### ISSUE TITLE
Set maximum value on primary measure axis

### ISSUE THREAD

**Issue by haydenlak** [google/charts#115]
Is there a parameter to fix the maximum value on the axis? I'm currently using desiredTickCount as a hack but I ideally only want 3 tickers (0,5,10) for a range of 0-10 on the measure axis.

**Comment by lorrainekan** [comment]
If you have a specific set of ticks that you want, consider using statically provided ticks.

https://google.github.io/charts/flutter/example/axes/statically_provided_ticks
