### ISSUE TITLE
Code is not latest version! Careful if you create pull requests.

### ISSUE THREAD

**Issue by jeroentrappers** [google/charts#138]
The code in this repo is 0.3.0. The version on dart packages is 0.4.0. I have had to reimplement some of my fixes after including the downloaded packages and changing them. 

I don't understand why the latest version has not been pushed here, when it has been published on dart packages on 2018-08-06. This is causing confusion.

**Comment by asaarnak** [comment]
Looks like sync branch is not merged into master: 
active branch: 17 commits ahead with version 0.4.0: https://github.com/google/charts/tree/90A7935A464224EA49F27B41988006AB

**Comment by lorrainekan** [comment]
Thanks for warning people, there was a sync mistake that as you noted that will be fixed in this pull request.
