### ISSUE TITLE
Text Overlay - Bar Chart

### ISSUE THREAD

**Issue by sky-tiagoalves** [google/charts#139]
There seems to be an issue with text overlay on the bottom when using Bar Charts.
![image](https://user-images.githubusercontent.com/16562735/46041994-263b7800-c10c-11e8-83f9-25a54fcdff2a.png)
(labels are going from 12am to 11pm)
Tried to hide some of the labels, but it would just not show any labels. My series are defined like this
`series = [
        new charts.Series(
          id: 'CallsByHour',
          colorFn: (_, __) => charts.MaterialPalette.red.shadeDefault,
          domainFn: (GraphItemCallsPerDay clickData, _) => clickData.date,
          measureFn: (GraphItemCallsPerDay clickData, _) => clickData.count,
          data: graphData,
        ),
      ];`

Any idea how to solve this? I'm ok with hiding some of the labels, just don't want to have a scroll to the side to see the rest of the values.

**Comment by lorrainekan** [comment]
The domain looks like a time, so consider using a time series chart with bar renenderer
https://google.github.io/charts/flutter/example/time_series_charts/with_bar_renderer

Another way to to provide a static set of ticks
https://google.github.io/charts/flutter/example/axes/statically_provided_ticks

**Comment by jlcool** [comment]
@lorrainekan How to display text vertically？

**Comment by jlcool** [comment]
@lorrainekan Attempt to add \ n, but text with numbers, the number cannot be in the middle
