### ISSUE TITLE
Support for Area Chart

### ISSUE THREAD

**Issue by willladislaw** [google/charts#148]
Consider adding Area Chart to the collection.

**Comment by willladislaw** [comment]
Consider adding Area Chart to the package.

**Comment by lorrainekan** [comment]
We already have this. Please visit the gallery for the example.
https://google.github.io/charts/flutter/example/line_charts/stacked_area

**Comment by willladislaw** [comment]
Created Chart 1 (see below) using [highcharts](https://highcharts.com), Chart 2  with flutter charts (same data).  Can't find any sample that look anything like Chart 1. Can see an example?

chart 1 
<img width="291" alt="screen shot 2018-10-09 at 11 52 40" src="https://user-images.githubusercontent.com/22636642/46665126-d86a4980-cbba-11e8-8267-dafc4287aaee.png">

chart 2
<img width="376" alt="screen shot 2018-10-09 at 11 52 57" src="https://user-images.githubusercontent.com/22636642/46665139-e61fcf00-cbba-11e8-8a32-6b05e9bfaec9.png">


json
{
  "volume1":{
    "2017-01-31":50,
    "2017-03-01":1,
    "2017-02-06":1},
  "volume2":{
    "2017-01-31":5,
    "2017-03-15":1,
    "2017-02-22":1,
    "2017-02-26":1
  },
}
