### ISSUE TITLE
Is it possible to set vertical axis range?

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [google/charts#216]
When my chart has both positive and negative values and the maximum value is N, then the Y axis range will be set from N to -N.

![Problem with Y axis](https://i.imgur.com/Lay7wZO.png)

I don't know if this is working as intended, but I'd like to be able to set the range for the Y axis and I can't seem to find any info on how to do this.

Edit: found a way to do it.
```
var someMinValue = -2.5;
staticTicks = <charts.TickSpec<double>>[
      new charts.TickSpec(someMinValue),
      new charts.TickSpec(0.0, label: "0.0"),
      new charts.TickSpec(5.0, label: "5.0"),
      new charts.TickSpec(10.0, label: "10.0"),
];
dayChart = new charts.TimeSeriesChart(
      // snipped usual chart stuff
      primaryMeasureAxis: new charts.NumericAxisSpec(
            tickProviderSpec: new charts.StaticNumericTickProviderSpec(staticTicks)
      ),
);
```

**Comment by oligazar** [comment]
@FineTillYouCameAlong I have the same problem. Were you able to find the solution?
