### ISSUE TITLE
Support null data

### ISSUE THREAD

**Issue by seddonm1** [google/charts#31]
Currently if a chart Series contains a null point an exception is thrown (for line charts at least) here: https://github.com/google/charts/blob/master/charts_common/lib/src/chart/line/line_renderer.dart#L223

This can be prevented by checking for nulls in the either domainValue and measureValue calls before the values are added to the pointList:

https://github.com/google/charts/blob/master/charts_common/lib/src/chart/line/line_renderer.dart#L145
```
        final domainValue = domainFn(datum, index);
        final measureValue = measureFn(datum, index);
        if (domainValue != null && measureValue != null) {
          pointList.add(_getPoint(datum, domainValue, series, domainAxis,
              measureValue, measureOffsetFn(datum, index), measureAxis));
        }
```

It is not beautiful but at least it prevents the chart from not displaying due to missing data.

**Comment by palkatap** [comment]
I would rather change the line_painter.dart. I made the fix also for dashed lines.
Attached you find my changes as path 
[Support null data #31.patch.txt](https://github.com/google/charts/files/2081113/Support.null.data.31.patch.txt)

**Comment by lorrainekan** [comment]
We support null values now, here is a simple example

https://google.github.io/charts/flutter/example/line_charts/simple_nulls
