### ISSUE TITLE
Is there any way to add action when I tap on a bar in BarChart?

### ISSUE THREAD

**Issue by fauzipadlaw** [google/charts#327]
I'm trying to create action when I tap on a bar in the bar chart it brings to another page. Is it possible to do that with this plugin?

**Comment by pasanlive** [comment]
@fauzipadlaw You can use 
` selectionModels: [
                              charts.SelectionModelConfig(changedListener:
                                  (charts.SelectionModel model) {
// add action here
}`

**Comment by Mmisiek** [comment]
For some reason event is not triggering in my tree. I have Grid with Container with PieChart.
