### ISSUE TITLE
TimeSeriesChart display all the 24 hours in the DomainAxis

### ISSUE THREAD

**Issue by bobosette** [google/charts#390]
Hi everybody. I'm trying to set a charts on my app and I want the charts to display 24 ticks for the 24 hours. I'm trying like this but the result 1 tick every 3 hours (3am, 6am, 9am ecc...). 

return new charts.TimeSeriesChart(dataChart2,
          animate: true,
          behaviors: [
            new charts.SlidingViewport(),
            new charts.PanAndZoomBehavior(),
          ],
          domainAxis: charts.DateTimeAxisSpec(
            tickFormatterSpec: charts.AutoDateTimeTickFormatterSpec(
              hour:
                  charts.TimeFormatterSpec(format: 'H', transitionFormat: 'H'),
              /*minute: new charts.TimeFormatterSpec(
                format: 'HH', // or even HH:mm here too
                transitionFormat: 'HH:mm',
              ),*/
            ),
          ));

How could i do it?

Thank u

**Comment by bobosette** [comment]
Incredible. I found the solution: https://github.com/google/charts/issues/287#issuecomment-521484763 !!! Now it works great, also the PanAndZoomBehaviour

**Comment by AmalinaMakhtar** [comment]
@bobosette can share how do you manage to resolve this issue?
