### ISSUE TITLE
Displaying the secondary measure axis while keeping the relation

### ISSUE THREAD

**Issue by hartmannj** [google/charts#41]
Not sure if it's the right place here to ask. It might be a feature which I haven't discovered or doesn't exist yet.
I am wondering if it is possible to display the secondary measure axis without losing the relation to the first dataset? As soon as I add `..setAttribute(charts.measureAxisIdKey, secondaryMeasureAxisId)` to the second dataset, the relation to the first doesn't exist anymore.
If that isn't possible, would there be a way to customize the primaryMeasureAxis label with a custom string and different colors within?

**Comment by lorrainekan** [comment]
When you set a series attribute to use the secondary measure axis, it will not use the primary measure axis. You can see an example of customizing font and color of axis here

https://google.github.io/charts/flutter/example/axes/custom_font_size_and_color

**Comment by hartmannj** [comment]
Yes, actually displaying a secondary measure axis is great, however it would be nice to have an option to keep the relation.
In my use case I want to display a currency course with two different currencies but since I use a nonzero bound measure axis a spike in one series might look a lot more severe than on the other one depending on the scale of the measure axis. So a "normalized" measure axis to lock both of the series would be very handy.

The link you've provided is not really helpful since you can only set one color and there is no example how to customize the measure axis labels, e.g. "8000 USD / 1 BTC" to reflect values of both series on one axis.

**Comment by lorrainekan** [comment]
https://google.github.io/charts/flutter/gallery.html

Please scroll down to "axes" and look for custom tick formatters to format the measure axis labels.
