### ISSUE TITLE
Percent axis not visible when using dark mode 

### ISSUE THREAD

**Issue by essarn** [google/charts#433]
I have a stacked bar chart with a percent axis. When the app is using `Brightness.dark` is the percent axis not visible, it's still black, ie. not adapting the color for the dark theme.

**Comment by EdYuTo** [comment]
I had a similar problem, try adding something like this to your BarChart() arguments:
```dart
domainAxis: charts.PercentAxisSpec(
          renderSpec: charts.SmallTickRendererSpec(
            labelStyle: charts.TextStyleSpec(
              color: charts.MaterialPalette.white,
            ),
          ),
        ),
```

**Comment by essarn** [comment]
Late response but thank you got it working.
