### ISSUE TITLE
Custom measure axis labels

### ISSUE THREAD

**Issue by hartmannj** [google/charts#46]
I am wondering if there is a way to generate custom measure axis labels. The solution right now is to use a `BasicNumericTickFormatterSpec` which expects a `NumberFormat` (e.g.: https://google.github.io/charts/flutter/example/axes/custom_axis_tick_formatters).
However, formatting the value and providing a currency symbol in front of it is not always enough.

One solution I could imagine is to support extending a `TickFormatter` so that the function `String formatValue(num value)` can be overridden.

Related and closed issue: https://github.com/google/charts/issues/41

**Comment by lorrainekan** [comment]
The latest sync exposes` SimpleTickFormatterBase<D>`, which can be extended to format D to whatever you choose. You will also need to create a corresponding `TickFormatterSpec<D>`. If you are formatting numeric values, I suggest you extend `SimpleTickFormatterBase<num>` and implement  `NumericTickFormatterSpec`
