### ISSUE TITLE
Primary Measure Axis extends outside of viewport

### ISSUE THREAD

**Issue by nigel25840** [google/charts#494]
I need to use this chart library but am having trouble with the primary measure axis extending outside of the viewport. I need the measure axis to start at a number greater than zero, which I have achieved, however, I cannot find a way to keep the axis from extending outside of the view port. Is there a way to do this? In the case of the attached screen shot, the measure axis should not extend outside of the green area. Is there a property that controls this behavior? 
![image](https://user-images.githubusercontent.com/4077631/85231776-f6e09a80-b3c7-11ea-93e7-1e930c514dad.png)

**Comment by Ajorona** [comment]
Did you figure this out @nigel25840?
