### ISSUE TITLE
How to make chart tick marks square/rectangle instead of the default grey horizontal line?

### ISSUE THREAD

**Issue by willladislaw** [google/charts#524]
I need the background to have a rectangle instead of that horizontal grey line.

![tickmarks-ppt_01](https://user-images.githubusercontent.com/22636642/88807499-b5eb5b00-d1a9-11ea-9313-0e7dcd9dcdaf.png)

**Comment by hijjkd** [comment]
like this?
![image](https://user-images.githubusercontent.com/26186197/97837574-6d4bbc80-1d19-11eb-9a06-a24ba3695fbe.png)

**Comment by hijjkd** [comment]
like this? 
<img width="338" alt="DX-20201102@2x" src="https://user-images.githubusercontent.com/26186197/97837653-9d935b00-1d19-11eb-868b-e752115de21e.png">

**Comment by willladislaw** [comment]
No. I'm talking about the background not the chart itself.

**Comment by willladislaw** [comment]
No. I'm talking about the background not the chart. Your version is missing the grey lines. I need background to be rectangle instead of line.

**Comment by hijjkd** [comment]
may i ask you question ?how to delete the title ?
![image](https://user-images.githubusercontent.com/26186197/98002993-2baa3700-1e29-11eb-8582-04c5b66092b9.png)

**Comment by willladislaw** [comment]
Have a look at the [examples](https://google.github.io/charts/flutter/gallery.html) without the chart legend defined on top of the page.

**Comment by willladislaw** [comment]
Have a look at the [examples](https://google.github.io/charts/flutter/gallery.html) without the chart legend defined specifically the ones at the top of the page.

**Comment by hijjkd** [comment]
thanks！ i got it .
