### ISSUE TITLE
Remove gap between stacked bars

### ISSUE THREAD

**Issue by LuisCampos97** [google/charts#548]
Hi!
How do I remove the white space (gap) between the stacked bars?

![image](https://user-images.githubusercontent.com/33434500/95852956-867dd080-0d4c-11eb-868f-4800d77c5293.png)

Thank you

**Comment by Ruben2112** [comment]
Did you find a solution for this?

**Comment by LuisCampos97** [comment]
Hi @Ruben2112!
No, I decided to look at other charts packages like fl_chart or syncfusion_flutter_charts.

**Comment by ali262883** [comment]
`defaultRenderer: charts.BarRendererConfig(
        stackedBarPaddingPx: 0,
        groupingType: charts.BarGroupingType.groupedStacked,
      ),`
