### ISSUE TITLE
How to set the fixed width of each item in the bar chart?

### ISSUE THREAD

**Issue by hijjkd** [google/charts#554]
Background: The data is variable, it could be 1, or 10.I want to make each item with 20px 。
How to set the width of each item to be a certain, for example, 20px for each bar graph？

**Comment by 18316603765** [comment]
源码MaterialStyle最后一行的rangeBandSize代表每一项所占的百分比，你根据这个查看修改源码就可以

**Comment by hijjkd** [comment]
> 源码MaterialStyle最后一行的rangeBandSize代表每一项所占的百分比，你根据这个查看修改源码就可以
感谢，方法有效。
