### ISSUE TITLE
Axes titles

### ISSUE THREAD

**Issue by qbait** [google/charts#571]
Is there an easy way to add axes titles using the library or I need to do it myself? (e.g. by adding additional `Text` widgets on `Stack`)

**Comment by edhom** [comment]
@qbait `LineAnnotationSegment` has the properties `startLabel` and `endLabel` that you can use. You define a `LineAnnotationSegment` for every axis an pass them to `behaviors` via `RangeAnnotation`.

**Comment by qbait** [comment]
Thank you!
