### ISSUE TITLE
Please update intl dependencies to > 0.17.0

### ISSUE THREAD

**Issue by thetayne** [google/charts#587]
Some packages require intl > 0.17.0 and this leads to incompatibility with charts_flutter 0.9.0

**Comment by evandrmb** [comment]
Hi, if you're interested in some workaround while the contributors don't update this package, look at issue #579. 
You can either override dependency or follow the steps in this comment:
https://github.com/google/charts/issues/579#issuecomment-754766439

**Comment by mit-mit** [comment]
Fixed in https://github.com/google/charts/pull/605
