### ISSUE TITLE
When will this package be updated?

### ISSUE THREAD

**Issue by tulioccalazans** [google/charts#588]
There are a lot of PRs and the community is asking for updates, as the last update was made on February 28, 2020.

**Comment by zerox1212** [comment]
Seems to be abandoned. I have seen people creating new chart libraries since this one is no longer active...

**Comment by porfirioribeiro** [comment]
It would be nice from Google to make some statement about this.
I haven't found any good alternative to this library.

It's still working good, but it starts having problems with library updates and NNBD migration

**Comment by junger92** [comment]
when this come null safty?

**Comment by kevlar700** [comment]
If a simple fix like #598 is ignored for longer than a couple of weeks. Then I guess we need to move on or create a community fork. Maybe in the longer term but I can't spare the time in the short term unfortunately. We also provide grafana access anyway. Not very touch friendly but alleviates some urgency.

**Comment by kevlar700** [comment]
https://github.com/google/charts/issues/606#issuecomment-795644160

**Comment by Inshaf111** [comment]
when will it be updated with null-safety?

**Comment by josxha** [comment]
@Inshaf111 https://github.com/google/charts/issues/579#issuecomment-817792878

**Comment by mit-mit** [comment]
https://pub.dev/packages/charts_flutter/versions/0.11.0
