### ISSUE TITLE
How to use variation in charts?

### ISSUE THREAD

**Issue by jeffersonmello** [google/charts#597]
Hello, i need to use variations how examples bellow:

![image](https://user-images.githubusercontent.com/17181273/109690319-fc9c9b80-7b64-11eb-92bb-5a196453b5fb.png)

![image](https://user-images.githubusercontent.com/17181273/109690379-0b834e00-7b65-11eb-9b08-ba663bcc9f76.png)

its possible?

**Comment by leynier** [comment]
@jeffersonmello Some like that?

![image](https://user-images.githubusercontent.com/36774373/110258247-a1f1ae00-7f6f-11eb-92d0-fda603550a07.png)

**Comment by leynier** [comment]
https://github.com/covid19cuba/covid19cuba-app/blob/0e8bd65edc627d3a18cf1838ddc9c646430ff1b3/lib/src/widgets/effective_reproductive_number_widget.dart#L63

**Comment by jeffersonmello** [comment]
> @jeffersonmello Some like that?
> 
> ![image](https://user-images.githubusercontent.com/36774373/110258247-a1f1ae00-7f6f-11eb-92d0-fda603550a07.png)

Exactly! thanks

**Comment by leynier** [comment]
@jeffersonmello I think that this issue should be closed
