### ISSUE TITLE
Update dependency on intl package

### ISSUE THREAD

**Issue by sebastianbuechler** [google/charts#599]
When using the new flutter 2.0.0 version I get the following error:
`Because charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0 and no versions of charts_flutter match >0.9.0 <0.10.0, charts_flutter ^0.9.0 requires intl >=0.15.2 <0.17.0.`

Is it possible to update the dependency of charts_flutter to a newer version of the intl package (>=0.17.0)?

**Comment by sebastianbuechler** [comment]
Seems like PR is already open: #598

**Comment by tony123S** [comment]
@sebastianbuechler have you found a way to fix ? I can't even run my project now because of this issue ...

**Comment by sebastianbuechler** [comment]
@tony123S Yes, either wait for the PR to merge or downgrade flutter to 1.22.6

**Comment by kevlar700** [comment]
@sebastianbuechler 
#566


#582 
#587

**Comment by sebastianbuechler** [comment]
> @sebastianbuechler
> @tony123S
> #566
> 
> #582
> #587

Maybe it makes more sense to reference the PR instead of just creating multiple references with the same issue.

**Comment by tony123S** [comment]
> @tony123S Yes, either wait for the PR to merge or downgrade flutter to 1.22.6

I using 1.22.6,still hitting same problem.

**Comment by sebastianbuechler** [comment]
> > @tony123S Yes, either wait for the PR to merge or downgrade flutter to 1.22.6
> 
> I using 1.22.6,still hitting same problem.

Then this would be another issue. I opened this issue because of the upgrade to Flutte 2.0.0 which requires intl version 0.17.0 but charts_flutter can not work with this version.

**Comment by tony123S** [comment]
> @sebastianbuechler
> @tony123S
> #566
> 
> #582
> #587

thanks, this helped.
