### ISSUE TITLE
After flutter upgrade to 2.0.1 chart_flutter is incompatible

### ISSUE THREAD

**Issue by benadrasni** [google/charts#600]
Because charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, charts_flutter 0.9.0 is incompatible with flutter_localizations from sdk.

**Comment by koji-1009** [comment]
Duplicated #566 and more...

**Comment by iamjay** [comment]
This project probably belongs to https://killedbygoogle.com/ now.

**Comment by mit-mit** [comment]
Fixed in https://github.com/google/charts/pull/605

**Comment by talamaska** [comment]
Yahooo! Thank you so much. I'm encouraged now to continue using this package and hope that soon the new version will be released. I see quite a lot of changes and it seems there is no new version released right? Can we hope or a change log? I see things merged not related to the null safety migration, like being possible to select all the overlapping point.
