### ISSUE TITLE
Flutter 2.0  intl version compatible

### ISSUE THREAD

**Issue by xiaohaoWit** [google/charts#602]
intl: '>=0.15.2 < 0.17.0'

**Comment by ghenry** [comment]
Same

**Comment by chakery01** [comment]
me too, please update version

**Comment by xtel-hilmar** [comment]
... and because charts_common >=0.4.0 <0.8.1 depends on intl ^0.15.2 and every version of flutter_localizations from sdk depends on intl 0.17.0, **_charts_flutter is incompatible with flutter_localizations_** from sdk :(

**Comment by mit-mit** [comment]
Fixed in https://github.com/google/charts/pull/605

**Comment by chakery01** [comment]
thank you ka
