### ISSUE TITLE
Need version update/bump for latest PR effect on pub dev

### ISSUE THREAD

**Issue by hey24sheep** [google/charts#606]
Thanks @cbbraun for [this](https://github.com/google/charts/pull/605). We need a version bump for this to be effective. I am still unable to use this package from pub.dev instead of changing deps to git.

**Comment by rubensbarreto** [comment]
Issue is currently blocking compatibility with Flutter 2.0, due to the intl dependency, already merged.

**Comment by EndersonSS** [comment]
Any idea when it will be available, support null safety ??

**Comment by EndersonSS** [comment]
Any idea when it will be available, support null safety ?

**Comment by cbbraun** [comment]
Sorry for the publishing delay. I ran into problems publishing the packages before (I didn't have an environment with dart even installed).

As mentioned in a comment on another issue, there is no one officially assigned to this project ATM. I'm trying to find a new owner that can carry the torch. Even the bump in intl took like 4 hours fighting setting up a local environment to make such a simple change (to be fair a bunch of that was addressing conflicts between a year's worth of internal source changes and github source).

I'll do what I can to support, but please understand there are internal dynamics and project priorities that make it difficult to spend much time on this. I'm going to see if I can timebox a certain amount of time every other week to review pull requests, but larger changes like null safety are unlikely to get done by myself given commitment to the project I'm actually assigned to.

**Comment by hey24sheep** [comment]
@cbbraun thank you so much. I understand, but it would help if someone could just check and approve public prs maybe once a while. That would help too. But, once again thanks a lot for you time and help.

**Comment by devmgs** [comment]
This is a great repo. Don't take me wrong cant it be shifted to flutter development team. They are maintaining a large number of repos. And this one is the only flutter chart library that is free licensed and works without a fail. May be they agree to maintain this at-least for primary issues such as compatibility like null safety if they don't want to add new functionality.
