### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by EndersonSS** [google/charts#607]

**Comment by kevlar700** [comment]
It's a fairly significant package and uses generics so likely a significant amount of work. I do wonder how much performance, might be gained though.  There is already an open issue.

#579

**Comment by larssn** [comment]
@EndersonSS Mind closing this so there isn't too many redundant issues?

**Comment by larssn** [comment]
> > @EndersonSS Mind closing this so there isn't too many redundant issues?
> 
> no problems

You have to close it. 😁
