### ISSUE TITLE
Fallback when seriesList is empty

### ISSUE THREAD

**Issue by bambinoua** [google/charts#611]
Is there any fallback funcitonality to display a chart when there are no series?

**Comment by kevlar700** [comment]
I use Dart to load a widget or chart depending on state. The issue tracker is for bugs. I am just a user also but questions should be made in other forums.

**Comment by bambinoua** [comment]
> I use Dart to load a widget or chart depending on state.

I have sense to have a built-in feature, isn't it?

> questions should be made in other forums.

I would be glad to know _what are other forums_.

**Comment by kevlar700** [comment]
Yeah. I'm not sure what the ideal forum is. I got some answers to questions I had on the flutter mailing list.
