### ISSUE TITLE
Supportt Flutter 2

### ISSUE THREAD

**Issue by buimanhhungit** [google/charts#626]
pls support flutter 2

**Comment by aifrosals** [comment]
This is an amazing repo. I hope it will get continuous support.

**Comment by GeorgeS19231** [comment]
> pls support flutter 2

You can find a stack in the closed issues, a lot of people are still waiting

**Comment by mit-mit** [comment]
Supported as off 0.11.0:
https://pub.dev/packages/charts_flutter/versions/0.11.0
