### ISSUE TITLE
please do add support for null saftey.

### ISSUE THREAD

**Issue by Abin-Thankachan** [google/charts#628]

**Comment by rahulrkhot** [comment]
null safety required

**Comment by GitRubb** [comment]
Anyway to run the app with null safety with the existing version of charts_flutter?

Also is this even in development anymore?

**Comment by Abin-Thankachan** [comment]
> Anyway to run the app with null safety with the existing version of charts_flutter?
> 
> Also is this even in development anymore?

Yes you use // @dart=2.9  as the 1st line of the file that depends on this package without disabling null safety for other areas.

**Comment by johnpryan** [comment]
This is a duplicate of https://github.com/google/charts/issues/579

**Comment by cbbraun** [comment]
Duplicate of #579
