### ISSUE TITLE
Null safety version?

### ISSUE THREAD

**Issue by ultrasandbox** [google/charts#637]
Hello,

 When will the null safety version be available?

**Comment by johnpryan** [comment]
See https://github.com/google/charts/issues/579

**Comment by conall1995** [comment]
yes please migrate to null safety

**Comment by surveshoeb** [comment]
Waiting for nullsafety

**Comment by Ohpizarro** [comment]
Buen día, tendrán entre sus planes a corto plazo realizar migración a nullsafety?. Espero su respuesta para mantener su excelente librería o planificar con antelación un cambio de librería en mi app.

**Comment by suyie001** [comment]
waiting for nullsafety

**Comment by dwivediavs** [comment]
add null safety please

**Comment by Rubywai** [comment]
I am waiting

**Comment by ciamax** [comment]
Waiting

**Comment by tadappnative** [comment]
waiting

**Comment by juanagu** [comment]
News?

**Comment by dwivediavs** [comment]
in my app there is only package without null safety......
waiting for its update

**Comment by connectprabhjeet** [comment]
Please migrate to null safety

**Comment by Josua2012** [comment]
Please migrate to null safety.
Thanks.

**Comment by vinukn335** [comment]
Please migrate to null safety.
Thanks.

**Comment by kirill20123456** [comment]
Please migrate to null safety.
Thanks.

**Comment by DreamLCM** [comment]
Waiting Waiting Waiting Waiting Waiting

**Comment by rahulrkhot** [comment]
Waiting... Please migrate to null safety.

**Comment by cbbraun** [comment]
I believe today's commit should address null safety. I still need to publish, but waiting for some validation before I publish since I'm bringing over other people's changes and it was not insignificant.
