### ISSUE TITLE
Error: The getter 'body1' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by Wissperwind** [google/charts#652]
Hi,

Please check out the most recent flutter version.
body1 is deprecated and now removed. Please change to bodyText1 and make a new Version.
The package is completly broken at the moment.

**Comment by talamaska** [comment]
@cbbraun to be clear. There is only one place that the deprecated text style is used - in legend entry.
https://github.com/google/charts/blob/26b73c62ae33d481f38a1f0c65f30f5e0c998126/charts_flutter/lib/src/behaviors/legend/legend_entry_layout.dart

**Comment by Piinks** [comment]
I think this is due to https://github.com/flutter/flutter/pull/83924, which was reverted in https://github.com/flutter/flutter/pull/86171 due to breaks like this. I have is re-staged in https://github.com/flutter/flutter/pull/86186, and I'm migrating folks that are affected now.

**Comment by talamaska** [comment]
I though that these styles were deprecated months ago.

**Comment by Piinks** [comment]
> I though that these styles were deprecated months ago.

Yes, they were. They are now being removed as the deprecation period has ended.

**Comment by Wissperwind** [comment]
Okay, since you use it only in one place, could you please release a new version?
I am at the newest version on the master branch and I still can't use this version to build, because as far as I can see the commit is still in there. I am at 2.4.0-5.0.pre.55 • channel master.

**Comment by ChristopheVersieux** [comment]
Still havinng the issue with latest version 0.11.0

charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.

**Comment by sbbird** [comment]
Anyway to bypass this issue?

**Comment by RonanLB** [comment]
The override worked for a while but now I'm getting this new error:


Error on line 18, column 11: Invalid description in the "charts_flutter" pubspec on the "charts_common" dependency: "../charts_common/" is a relative path, but this isn't a local pubspec.
   ╷
18 │     path: ../charts_common/
   │

**Comment by arnoorani** [comment]
@RonanLB  yup same issue, getting the same error today. hopefully they fix it soon

**Comment by angel-arcos** [comment]
@arnoorani 

got this fixed, look at your pubspec.yaml and remove the reference to the github repo, use the released library package instead of the repo one (related to #710)

```
  charts_flutter: ^0.11.0
#    git:
#      url: https://github.com/google/charts
#      path: charts_flutter
```

**Comment by Ronjack** [comment]
same issue here

**Comment by Ronjack** [comment]
emporary solved with this:

charts_flutter:
git:
url: http://github.com/google/charts.git
path: charts_flutter
ref: 03c2aa6

**Comment by angel-arcos** [comment]
> emporary solved with this:
> 
> charts_flutter: git: url: [http://github.com/google/charts.git](https://github.com/google/charts.git) path: charts_flutter ref: [03c2aa6](https://github.com/google/charts/commit/03c2aa67d12952e7f3cbba1d87646d96a9a7cdc4)

Not working here with this workaround :(

**Comment by arnoorani** [comment]
@Ronjack @RonanLB  both these solutions work. Thanks so much

**Comment by arnoorani** [comment]
> > emporary solved with this:
> > charts_flutter: git: url: [http://github.com/google/charts.git](https://github.com/google/charts.git) path: charts_flutter ref: [03c2aa6](https://github.com/google/charts/commit/03c2aa67d12952e7f3cbba1d87646d96a9a7cdc4)
> 
> Not working here with this workaround :(

in case you are adding it in dev_dependencies,  remove it from there. at least it worked for me.

**Comment by domesticmouse** [comment]
Please use `charts_flutter: ^0.12.0`

**Comment by nirancodelab** [comment]
> Please use `charts_flutter: ^0.12.0`

Yyep. This worked for me. Thanks.

**Comment by Kanishka-Bandara** [comment]
> > Please use `charts_flutter: ^0.12.0`
> 
> Yyep. This worked for me. Thanks.

This works for me. Thanks :)
