### ISSUE TITLE
Error occurred on run - Had to change the code in my project

### ISSUE THREAD

**Issue by snirozery** [google/charts#661]
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.10.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
      color ??= Theme.of(context).textTheme.body1.color;
                                                                    ^^^^^
Failed to compile application.

I changed from body1 >> bodyText1 and now it's okay

**Comment by t1r** [comment]
Hello. I have same issue.
think this proplem:
https://github.com/google/charts/issues/652
Looks, like we need wait update.

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.4.0-5.0.pre.87, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
[✓] VS Code (version 1.58.0)
[✓] Connected device (2 available)
```

**Comment by snirozery** [comment]
It's was an issue with the chart_flutter package - fixed it locally and reported the creator

**Comment by snirozery** [comment]
.
