### ISSUE TITLE
Flutter pan and zoom on Windows application

### ISSUE THREAD

**Issue by adhendricks** [google/charts#680]
I am hoping for help getting the Pan and Zoom behavior to work on Windows. Whenever  I run the windows version of my code it refuses to pan or zoom. I greatly appreciate any help. The code is below.

//Start code
  mychart() {
    return Expanded(
      child: charts.LineChart(
        dataSeries,
        animate: true,
        behaviors: [
          charts.PanAndZoomBehavior(),
        ],
      ),
    );
  }

//End Code

I am running flutter 2.5.0

**Comment by a15056478** [comment]
How we show points on touching at any point of the line in series chart?How we show points on touching at any point of the line in series chart?

**Comment by adhendricks** [comment]
> How we show points on touching at any point of the line in series chart?

**Comment by adhendricks** [comment]
I am still not able to zoom in on the windows version of the application
