### ISSUE TITLE
Error on TextTheme class

### ISSUE THREAD

**Issue by mkeyyy** [google/charts#685]
I updated my flutter/dart sdk to 2.5.1... i have the latest chart library (charts_flutter: ^0.11.0) tried to run my app, got the following error:

'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/Users/Probook/AppData/Local/FlutterSDK/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
      color ??= Theme.of(context).textTheme.body1!.color;

**Comment by krishnaji-eGov** [comment]
Any update?

**Comment by khari998** [comment]
Getting the same error. 

body1 is deprecated on textTheme. Needs to be changed to bodyText1

**Comment by Dinesh-DK** [comment]
what did you guys do about it?

**Comment by Douglas47** [comment]
I'm having the same problem. Someone found any solution?

**Comment by Douglas47** [comment]
I found this other discussion, with a possible solution:

https://github.com/google/charts/issues/676#issuecomment-918119560

**Comment by khari998** [comment]
> I found this other discussion, with a possible solution:
> 
> [#676 (comment)](https://github.com/google/charts/issues/676#issuecomment-918119560)

Yes this worked for me as well. Its just a temporary solution until the package is updated on pub

**Comment by GlauberAlc** [comment]
my solution:
dependencies:
  flutter:
    sdk: flutter
  
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
