### ISSUE TITLE
Can't compile the app

### ISSUE THREAD

**Issue by acx70** [google/charts#687]
I get the following error when I compile my app:

../../../../flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.

FAILURE: Build failed with an exception.

---------------------------------

charts_flutter: ^0.11.0

---------------------------------

flutter --version:
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (7 days ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

**Comment by MiroslavPeterka1** [comment]
Same

**Comment by RedsAnDev** [comment]
same

**Comment by GlauberAlc** [comment]
My solution:

dependencies:
  flutter:
    sdk: flutter
    charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter

**Comment by acx70** [comment]
> 
> 
> My solution:
> 
> dependencies:
> flutter:
> sdk: flutter
> charts_flutter:
> git:
> url: git://github.com/google/charts.git
> path: charts_flutter

It works as temporary solution, but I think it should be fixed.
Note: you should add "publish_to: none" as follow:

`
publish_to: none

dependencies:
  flutter:
    sdk: flutter

charts_flutter: 
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
`

**Comment by hussamDana92** [comment]
same

**Comment by amarildox** [comment]
same problem

**Comment by ranthonissen** [comment]
Duplicate of #685

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/google/charts/issues/678
