### ISSUE TITLE
charts_flutter: ^0.11.0 is not supported in the latest version of flutter 2.5.1

### ISSUE THREAD

**Issue by rubanMosesExa** [google/charts#692]
charts_flutter: ^0.11.0 is not supported in flutter version 2.5.1 - 
When i recently updated  the flutter version to 2.5.1 some of the packages were deprecated and i was able to get an alternative for them.
But i did not get any alternative for this package and when ever i try to run the flutter code i get the below error.
Should i wait for the developer of this package to update the package ? Thanks in advance !

![Screenshot 2021-09-30 at 11 26 33 AM](https://user-images.githubusercontent.com/70621861/135395513-4aba2309-cdb9-4e5b-8925-a38fecec2412.png)

**Comment by tafkag** [comment]
The workaround from #676 worked for me.

**Comment by rubanMosesExa** [comment]
Thank You very much #67 worked for me
