### ISSUE TITLE
flutter pub upgrade issue

### ISSUE THREAD

**Issue by caoyuanyuan** [google/charts#716]
In my pubspec.yaml, i  was added a line that "charts_flutter: ^0.11.0".But when i execute pub upgrade, it not upgraded to v0.12.0.

**Comment by domesticmouse** [comment]
Major version zero is handled differently, in effect moving from 0.11.0 to 0.12.0 is considered a major version upgrade. You'll need to update it in your pubspec.

**Comment by caoyuanyuan** [comment]
OK,I understanded,thanks.
