### ISSUE TITLE
Charts Docs needs to be updated

### ISSUE THREAD

**Issue by 2002Bishwajeet** [google/charts#725]
Currently the example of all the [gallery charts](https://google.github.io/charts/flutter/gallery.html) seems to be outdated. 
They aren't null safe and these examples uses `new` keywords which is unnecessary after **flutter 1.8**.
Also they do not follow **best lint** practices.

Since this repo does not accept external [contributors ](https://github.com/google/charts/blob/master/CONTRIBUTING.md), I wasn't able to create a PR for the same.

Would love for the docs to be updated soon :)

**Comment by bkbonner** [comment]
+1

**Comment by eialanjones** [comment]
+1

**Comment by codexcer** [comment]
I agree with this

**Comment by palicka** [comment]
+1

**Comment by ShahanAhmedDev** [comment]
+1
