### ISSUE TITLE
How do I change the smoothness of line?

### ISSUE THREAD

**Issue by nevergoneok** [google/charts#80]
How do I change the smoothness of line?

**Comment by lorrainekan** [comment]
I am not sure what that means. If you mean the pattern of the line, see:
https://google.github.io/charts/flutter/example/line_charts/dash_pattern

**Comment by tsun424** [comment]
Hi @lorrainekan , I think `smoothness` means something like this:
https://developers.google.com/chart/interactive/docs/gallery/linechart#curving-the-lines

There is option `curveType` in that Google Charts, I didn't find similar option from source code of our charts.

**Comment by lorrainekan** [comment]
I see what you mean now. I am not aware of any current plans to add this.

**Comment by SilverJan** [comment]
Why is the issue closed even though it is not actually implemented? Shouldn't it be kept open?
