### ISSUE TITLE
How I can add label for chart bars?

### ISSUE THREAD

**Issue by CoMatu** [google/charts#81]
How I can add label for chart bars? Have you an example?

**Comment by lorrainekan** [comment]
do you mean labels inside the bar?
https://google.github.io/charts/flutter/example/bar_charts/horizontal_bar_label

do you mean axis ticks that correspond to each bar?
https://google.github.io/charts/flutter/example/axes/custom_axis_tick_formatters

the main gallery
https://google.github.io/charts/flutter/gallery.html

**Comment by CoMatu** [comment]
"do you mean labels inside the bar?" - No, I mean labels for vertical simple barchart. Like this 
![image](https://user-images.githubusercontent.com/30466272/43300211-4b6ab31c-9177-11e8-87fc-20d687b42068.png)

**Comment by lorrainekan** [comment]
Ah, I see. We have plans to add this but I don't have a timeline for when it will be available. We would likely augment the BarLabelDecorator to handle this case.

**Comment by Ahmadre** [comment]
We're in August 2019! It would be great if you look after this. Vertical Bar labels shouldn't be a problem, if you already got it for horizontal bars...

**Comment by RicardoAndroid** [comment]
I tried the example from the gallery and doesn't work
it gives me this error which gives me the impression that is not truly implemented
`══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19322): The following assertion was thrown during paint():
I/flutter (19322): 'package:charts_common/src/chart/bar/bar_label_decorator.dart': Failed assertion: line 73 pos 12:
I/flutter (19322): 'renderingVertically == false': is not true.`

**Comment by amerinoo** [comment]
Hi, I had the same problem as @RicardoAndroid . To solve it I've just updated the pubspec.yaml to the [lastest version](https://pub.dev/packages/charts_flutter).

> charts_flutter: ^0.8.1

Hope it works for you!
