### ISSUE TITLE
Deeclare compatibility with Dart 2 stable

### ISSUE THREAD

**Issue by mit-mit** [google/charts#95]
The Dart SDK constraints need to be updated to [declare compatibility with Dart 2 stable](https://www.dartlang.org/dart-2#upper-constraints-on-the-sdk-version):

1. https://github.com/google/charts/blob/master/charts_common/pubspec.yaml#L8
1. https://github.com/google/charts/blob/master/charts_flutter/pubspec.yaml#L8

**Comment by mit-mit** [comment]
cc @lorrainekan can you help with this? This is fairly urgent, as Dart 2 is now done.

**Comment by lorrainekan** [comment]
Done in #96
