### ISSUE TITLE
Gallery Is Messed Up

### ISSUE THREAD

**Issue by shoxter** [google/charts#97]
When I visit the online gallery (https://google.github.io/charts/flutter/gallery.html), there are no visuals and all the code displays in code blocks that take up one line making the gallery unusable.

See below:

![image](https://user-images.githubusercontent.com/19478126/43779970-8949a55e-9a27-11e8-8f9b-04ec600d13bd.png)

**Comment by lorrainekan** [comment]
Fixed in #98
