### ISSUE TITLE
What does domainLowerBoundFn do ? I tried using it in line chart but doesn't seem to work.

### ISSUE THREAD

**Issue by manujbahl** [google/charts#99]
My series list looks like this 
[
    {
          domain: "d1",
          valuesList: [
                     x: 2015, y: 12,
                     x: 2016, y: 29,
                     x: 2017, y: 35,
          ]
     },
    {
          domain: "d2",
          valuesList: [
                     x: 2015, y: 26,
                     x: 2016, y: 21,
                     x: 2017, y: 30,
          ]
     },
    {
          domain: "d3",
          valuesList: [
                     x: 2015, y: 33,
                     x: 2016, y: 22,
                     x: 2017, y: 15,
          ]
     },
]

In bar chart it works fine and starts the x axis at 2015. but in line chart the x axis starts at 0.

Also when i specify flipVerticalAxis to true, bar chart disappears and line chart is still above the y axis

**Comment by lorrainekan** [comment]
Please see the gallery. It's for symbol annotation and comparison point 

https://google.github.io/charts/flutter/gallery.html

Are you instead thinking of time series confidence interval? If so, we are working on that.

https://www.researchgate.net/figure/Time-series-plot-mean-and-confidence-interval-for-a-y-for-lane-change-left_fig5_284183616

**Comment by manujbahl** [comment]
not necessarily time series. It could be some other values on the x-axis. It looks like NumericExtents is the way to go. Am I right? Also what is the purpose of domainLowerBound  and upperbound

**Comment by manujbahl** [comment]
@lorrainekan  i dont know how to reopen the bug. Also since you are looking at the issues list .. i opened a couple quick ones for some questions I had ... 

https://github.com/google/charts/issues/105

https://github.com/google/charts/issues/102

**Comment by manujbahl** [comment]
And what I want to have a special function to customize the domain label to say "Year " + domain value. Is there a formatter to do that.

**Comment by mosleim** [comment]
is there update?
